name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_app_check: ^0.2.2+6
  provider: ^6.1.2
  go_router: ^14.2.0
  google_fonts: ^6.3.0
  google_generative_ai: ^0.4.2
  dynamic_color: ^1.8.1
  haptic_feedback: ^0.5.1+1
  animations: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
